print ("=============")
print ("   Biodata   ")
print ("=============")
#variabel
nama= input ("Masukan Nama Anda: ")
alamat= input ("Masukan Alamat: ")
ttl= input ("Masukan Tempat Tanggal Lahir Anda: ")
jk= input ("Jenis Kelamin: ")
agama= input ("Masukan Agama: ")
pekerjaan= input ("Pekerjaan: ")
hoby= input ("Masukan Hoby: ")
km= input ("Kata Mutiara: ")

#Menampilkan Inputan User
print ("============")
print ("Biodata Anda")
print ("============")
print ("Nama: ",nama)
print ("Alamat: ",alamat)
print ("Tempat Tanggal Lahir: ",ttl)
print ("Jenis Kelamin: ",jk)
print ("Agama: ",agama)
print ("Pekerjaan: ",pekerjaan)
print ("Hoby: ",hoby)
print ("Kata Mutiara: ",km)